### ISSUE TITLE
Logos einbinden

### ISSUE THREAD

**Issue by sigi2345** [HGlab01/ioBroker.fuelpricemonitor#249]
Hallo,

ist es möglich Tankstellen-Logos einzubinden?

FG
Sigi

**Comment by sigi2345** [comment]
Hallo, gibt es was Neues dazu?

**Comment by HGlab01** [comment]
Hallo! Bin mir nicht sicher, wie du das meinst...
Willst du einem State das Logo gespeichert haben? Die API "api.e-control.at" gibt keinen Link zu einem Logo oder ähnlichen und ich hab keine Kontrolle welche Tankstellen da retour gemeldet werden.
