### ISSUE TITLE
cheapest table

### ISSUE THREAD

**Issue by maximal1981** [HGlab01/ioBroker.fuelpricemonitor#250]
Hallo,

wäre schön wenn man auch eine Tabelle mit den am günstigsten hätte.

Theoretisch je 5 per Koordinaten, da ab dem 6.ten Eintrag keine Preise mehr enthalten sind.
Das würde dann z.B. für 3 Koordinaten 15 Einträge je Sprittype ergeben.

lg maximal1981

**Comment by HGlab01** [comment]
Hallo! Was meinst du mit Tabelle? Willst du in einem State alle Daten für eine Tabelle haben und formatiert nach Markdown?

**Comment by maximal1981** [comment]
Hallo.

Ich meine schon Datenpunkte nur einen Pfad wo mehrere Standort in sich aufsteigend geordnet sind.

zB (vereinfachte Darstellung):

0.Steyr.Super.1.price = 1,000
0.Steyr.Super.2.price = 1,600

0.Wels.Super.1.price = 1,200
0.Wels.Super.2.price = 1,700

0.Ybbs.Super.1.price = 1,100
0.Ybbs.Super.2.price = 1,400

würde eine 15 Punkte lange Liste ergeben mit:

0.overall.Super.1.price = 1,000   (=Steyr1)
0.overall.Super.2.price = 1,100   (=Ybbs1)
0.overall.Super.3.price = 1,200   (=Wels1)
0.overall.Super.4.price = 1,400   (=Ybbs2)
0.overall.Super.5.price = 1,600   (=Steyr2)
0.overall.Super.6.price = 1,600   (=Wels2)

somit kann man ein VIS schön dynamisch bauen und die Logos wären dann auch noch geil, aber da gibt es eh eine separate Anfrage.

Achja, ist es möglich eine Zahl auf 3 Nachkommastellen zu speichern auch wenn es 1,400 wäre. Kenn mich mit der var Deklaration nicht wirklich aus.

**Comment by HGlab01** [comment]
duplicate to #445

**Comment by HGlab01** [comment]
fixed in
https://github.com/HGlab01/ioBroker.fuelpricemonitor/releases/tag/v0.3.3-alpha.0
