### ISSUE TITLE
Expected "object", received "string"

### ISSUE THREAD

**Issue by maximal1981** [HGlab01/ioBroker.fuelpricemonitor#293]
js-controller update von 3.3.x auf 4.0.15

distance is invalid: obj.common.states has an invalid type! Expected "object", received "string"
open is invalid: obj.common.states has an invalid type! Expected "object", received "string"
fuelpricemonitor.0 | 2022-02-27 10:00:41.047 | warn | This object will not be created in future versions. Please report this to the developer.
fuelpricemonitor.0 | 2022-02-27 10:00:41.046 | warn | This object will not be created in future versions. Please report this to the developer.
otherServiceOffers is invalid: obj.common.states has an invalid type! Expected "object", received "string"
position is invalid: obj.common.states has an invalid type! Expected "object", received "string"
fuelpricemonitor.0 | 2022-02-27 10:00:41.045 | warn | This object will not be created in future versions. Please report this to the developer.
paymentArrangements.clubCard is invalid: obj.common.states has an invalid type! Expected "object", received "string"
paymentArrangements.cooperative is invalid: obj.common.states has an invalid type! Expected "object", received "string"
fuelpricemonitor.0 | 2022-02-27 10:00:41.042 | warn | This object will not be created in future versions. Please report this to the developer.
fuelpricemonitor.0 | 2022-02-27 10:00:41.043 | warn | This object will not be created in future versions. Please report this to the developer.
paymentMethods.others is invalid: obj.common.states has an invalid type! Expected "object", received "string"
paymentMethods.creditCard is invalid: obj.common.states has an invalid type! Expected "object", received "string"
fuelpricemonitor.0 | 2022-02-27 10:00:41.040 | warn | This object will not be created in future versions. Please report this to the developer.
fuelpricemonitor.0 | 2022-02-27 10:00:41.041 | warn | This object will not be created in future versions. Please report this to the developer.
paymentMethods.debitCard is invalid: obj.common.states has an invalid type! Expected "object", received "string"
paymentMethods.cash is invalid: obj.common.states has an invalid type! Expected "object", received "string"

**Comment by HGlab01** [comment]
A very good morning to you as well!
Thank you for you very detailed explanation, using the template and checking the change log before creating the issue.

I guess you are using a adapter version older then 0.2.10? (this info would be part of the template)

![image](https://user-images.githubusercontent.com/54232526/155877298-daa28b7c-df45-4852-bcb9-564221ff92d2.png)

**Comment by maximal1981** [comment]
you're probably Austrian or at least German, aren't you?
As far as I know, are other communications already in German?
but no problem, my current version is 0.2.9 and I'm not offered a newer one. I'm currently on stable.

**Comment by HGlab01** [comment]
0.2.10 will move to stable next week
