### ISSUE TITLE
Cannot parse JSON: undefined

### ISSUE THREAD

**Issue by Negalein** [HGlab01/ioBroker.fuelpricemonitor#36]
Seit 0.1.3 kommt im Sekundentakt folgende Meldung

`fuelpricemonitor.0	2021-02-21 14:25:01.526	error	(12300) Cannot parse JSON: undefined`

**Comment by HGlab01** [comment]
Hi! Kann ich nicht nachvollziehen bei meinen Installtionen.
Kannst du den Adapter bitte mal im Debug-Modus starten und das ganze Log schicken. Danke!

**Comment by HGlab01** [comment]
v0.1.4 released; wenn es noch auftritt dann bitte mit Loglevel "debug" starten und das Ticket wieder öffnen. Danke!
