### ISSUE TITLE
unter fuelpricemonitor.0.0_Home_Diesel nicht die billigste

### ISSUE THREAD

**Issue by Negalein** [HGlab01/ioBroker.fuelpricemonitor#365]
Hallo

Ich hab 5 Orte angelegt.
Unter `fuelpricemonitor.0.0_Home_Diesel` wird leider nicht die billigste angezeigt.

Enzenkirchen ist die billigste
![image](https://user-images.githubusercontent.com/45309436/184116830-154d1811-e73b-43c2-b9dc-a2d104e47207.png)

wird aber hier nicht berücksichtigt
![image](https://user-images.githubusercontent.com/45309436/184116947-78c5f359-5813-499b-943e-091b47961340.png)

**Comment by HGlab01** [comment]
Hallo! Welche Koordinaten nutzt du zur Ermittlung für Home? Damit ich es nachstellen kann

**Comment by Negalein** [comment]
> Hallo! Welche Koordinaten nutzt du zur Ermittlung für Home? Damit ich es reproduzieren kann

Ahhh halt.
Mit Home nimmt er die Koordinaten, die im Admin eingestellt sind?

Ich dachte unter Home zeigt er die 5 günstigsten aller eingestellten Orte!

Wäre dies dann möglich zu implementieren?

**Comment by HGlab01** [comment]
korrekt, Home ist dein zu Hause :-)
Ich schau mir mal an, wie einfach man einen weiteren Knoten implementieren kann der das günstigste aller Knoten zusammensammelt

**Comment by Negalein** [comment]
> korrekt, Home ist dein zu Hause :-) Ich schau mir mal an, wie einfach man einen weiteren Knoten implementieren kann der das günstigste aller Knoten zusammensammelt

Merci!
Das wäre echt nützlich!

**Comment by HGlab01** [comment]
you can test it in the version
https://github.com/HGlab01/ioBroker.fuelpricemonitor/releases/tag/v0.3.2-alpha.0
by using the checkbox
![image](https://user-images.githubusercontent.com/54232526/208081405-893b552c-e3e5-4cee-9a23-a96bce2c6edc.png)

**Comment by Negalein** [comment]
> you can test it in the version https://github.com/HGlab01/ioBroker.fuelpricemonitor/releases/tag/v0.3.2-alpha.0 by using the checkbox ![image](https://user-images.githubusercontent.com/54232526/208081405-893b552c-e3e5-4cee-9a23-a96bce2c6edc.png)

wie kann ich die Alpha installieren?

`$ iobroker url https://github.com/HGlab01/ioBroker.fuelpricemonitor/releases/tag/v0.3.2-alpha.0 --host ioBroker --debug

Cannot install from GitHub. Invalid URL https://github.com/HGlab01/ioBroker.fuelpricemonitor/releases/tag/v0.3.2-alpha.0

Process exited with code 0`

**Comment by HGlab01** [comment]
> wie kann ich die Alpha installieren?
> 
HGlab01/ioBroker.fuelpricemonitor#102c19505556e841aefd3786b35bc2600c2babde

**Comment by Negalein** [comment]
> HGlab01/ioBroker.fuelpricemonitor#102c19505556e841aefd3786b35bc2600c2babde

es bleibt bei 0.3.1

```
$ iobroker url https://github.com/HGlab01/ioBroker.fuelpricemonitor#102c19505556e841aefd3786b35bc2600c2babde --host ioBroker --debug

install HGlab01/ioBroker.fuelpricemonitor#25444dc9611942fb059592a0996fa4589f69f692

NPM version: 8.19.2

Installing HGlab01/ioBroker.fuelpricemonitor#25444dc9611942fb059592a0996fa4589f69f692... (System call)

up to date in 4s

183 packages are looking for funding run `npm fund` for details

upload [4] fuelpricemonitor.admin /opt/iobroker/node_modules/iobroker.fuelpricemonitor/admin/admin.d.ts admin.d.ts video/mp2t

upload [3] fuelpricemonitor.admin /opt/iobroker/node_modules/iobroker.fuelpricemonitor/admin/fuelpricemonitor.png fuelpricemonitor.png image/png

upload [2] fuelpricemonitor.admin /opt/iobroker/node_modules/iobroker.fuelpricemonitor/admin/index_m.html index_m.html text/html

upload [1] fuelpricemonitor.admin /opt/iobroker/node_modules/iobroker.fuelpricemonitor/admin/style.css style.css text/css

upload [0] fuelpricemonitor.admin /opt/iobroker/node_modules/iobroker.fuelpricemonitor/admin/words.js words.js application/javascript

Process exited with code 0
```

**Comment by HGlab01** [comment]
du hast es so versucht?
![image](https://user-images.githubusercontent.com/54232526/208096553-9330498b-9498-4f7b-9cd6-b24cca6b0a3c.png)
oder mit https://github.com/ vorne dran?
https://github.com/ gehört nicht hin

**Comment by Negalein** [comment]
> du hast es so versucht?

danke, funktioniert!
hatte es mit https://github.com/ vorne dran.

cheapest funktioniert!
Danke
