### ISSUE TITLE
Preis wird nicht angezeigt

### ISSUE THREAD

**Issue by der-eine** [HGlab01/ioBroker.fuelpricemonitor#380]
Hallo, 

leider werden manche Tankstellen doppelt aufgeführt (Lagerhaus) und manche haben keine Preis/Liter (BP und Lagerhaus).

<img width="2269" alt="Bildschirmfoto 2022-09-01 um 13 56 55" src="https://user-images.githubusercontent.com/42468286/187907805-c514f079-c51a-4de6-b2cb-7d86a5d34e76.png">

Koordinaten:
Latitude: 48.138751
Longitute: 12.849313

Kannst Du da mal bitte drüber schauen.

Danke

**Comment by HGlab01** [comment]
Preise gibt es nur für die ersten 5 gereihten.
Die zwei Lagerhaus sind nicht ident. Andere IDs, andere Entfernungen etc. Wenn du eine der beiden weghaben willst, müsstet du den Lagerhausbetreiber bitten das die Tankstelle zu schließen ;-)

**Comment by der-eine** [comment]
Danke für die ausführliche und nette Antwort! Was kann ich denn machen, dass das Lagerhaus auch unter den ersten 5 erscheint ausser die Koordinaten für die Stadt einzugeben. BP und Lagerhaus sind ca 1,5 km entfernt. Wie wird denn festgelegt wer unter die ersten 5 kommt? Entfernung zum angegebenen Standort?

**Comment by HGlab01** [comment]
wie die API genau funktioniert (ich nehme die Daten nur und speichere es als ioBroker-States) kann man hier
https://www.e-control.at/spritpreisrechner
nachlesen

**Comment by der-eine** [comment]
Ok, danke.
