### ISSUE TITLE
Latitude or Longitude not set in main configuration!

### ISSUE THREAD

**Issue by Berrny2311** [HGlab01/ioBroker.fuelpricemonitor#392]
Hallo,
leider bekomme ich ihn nicht zum laufen,
habe vollende Einstellungen:
![image](https://user-images.githubusercontent.com/63289459/192215414-1ff5703d-0416-447b-8a69-5816850c3307.png)

bekommen hier aber keine weiteren Einträge (Expertenmodus):
![image](https://user-images.githubusercontent.com/63289459/192215084-7d22d191-2ec9-46f8-a318-c5426ea4e00c.png)

Logs:
![image](https://user-images.githubusercontent.com/63289459/192216000-b276b4e0-aab1-425d-8f8b-77feae70a7db.png)

**Comment by HGlab01** [comment]
Die Koordinaten fehlen in den System Settings; also nicht im Adapter sondern global für ioBroker
![image](https://user-images.githubusercontent.com/54232526/192216488-e93f760f-79f4-4b16-8360-b6d9c2dfd63e.png)

![image](https://user-images.githubusercontent.com/54232526/192216608-bac6e62c-0d2e-4c66-b151-cbb563780d4f.png)

**Comment by Berrny2311** [comment]
Danke!
