### ISSUE TITLE
Billigste Tankstellen splitten Diesel/Benzin/usw..

### ISSUE THREAD

**Issue by thkn1973** [HGlab01/ioBroker.fuelpricemonitor#445]
Die Funktion ist super! 
Nur sollte man die noch Splitten auf die einzelnen Abgefragten Spritarten.
Bei mir werden 40 Benzin Tankstellen angezeigt aber keine Einzige mit Diesel.
Also sprich eine eigene Liste für Diesel Benzin usw....
LG

**Comment by HGlab01** [comment]
testbar über
HGlab01/ioBroker.fuelpricemonitor#8fbc2fbfffa7a9faa1b21e2883e92db90c235203
![image](https://user-images.githubusercontent.com/54232526/208240822-22463cbd-ac70-47a1-b0bf-80f910406a68.png)

Versionsnummer ist noch 0.3.2

**Comment by HGlab01** [comment]
Resolves #250

**Comment by HGlab01** [comment]
Solves #447
