### ISSUE TITLE
Billigste Tankstelle splitten und filtern

### ISSUE THREAD

**Issue by thkn1973** [HGlab01/ioBroker.fuelpricemonitor#447]
Hallo, funktioniert super mit dem Split.
Request wäre noch wenn möglich, da ja aus verschiedensten Locations alle aufs billigste gefiltert werden, 
das hier doppelte Tankstelle gleich heraus gefiltert werden.
Ich habe überschneidende Locations und somit 3mal die selbe Tankstelle als Nummer 1.
Thx

PS: sorry ich konnte in dem anderen Issue nicht mehr dazu kommentieren.

**Comment by HGlab01** [comment]
let's try
HGlab01/ioBroker.fuelpricemonitor#4c2defe0279edadfaab95e43ed781d5b01c572a9

**Comment by HGlab01** [comment]
Closes #250

**Comment by HGlab01** [comment]
fixed in
https://github.com/HGlab01/ioBroker.fuelpricemonitor/releases/tag/v0.3.3-alpha.0

**Comment by HGlab01** [comment]
Resolves #250
