### ISSUE TITLE
Error und Adapter bleibt Rot

### ISSUE THREAD

**Issue by Negalein** [HGlab01/ioBroker.fuelpricemonitor#51]
Bekomme diese Meldung bei 0.2.1

`host.iobroker | 2021-03-13 02:08:27.047 | error | startInstance system.adapter.fuelpricemonitor.0Invalid version of "js-controller". Installed "3.1.6", required ">=3.2.16`

**Comment by HGlab01** [comment]
Die Meldung ist Absicht und notwendig.
In älteren JS-Controller-Versionen funktioniert die Funktion getStates() nicht korrekt. Das wurde in der Version 3.2.16 gefixed. Daher ist diese Version als Minimum required.
Somit bitte die JS-Controller Version auf die Stable-Version 3.2.16 upgraden.
