### ISSUE TITLE
Sortierung der Objekte

### ISSUE THREAD

**Issue by fwolf22** [HGlab01/ioBroker.fuelpricemonitor#65]
Dere,

erstmal danke fürs entwickeln des adapters.
leider kann man bei der angegebenen email keine mails senden, es kommt immer ein error, dass die addy nicht existiert bzw keine mails empfangen kann... nur so am rande.

der grund hierfür:
ich hätte gern eine sortiermöglichkeit der spots, da er aktuell immer nach dem billigsten produkt sortiert. da ich aber den preis auch aufzeichnen will (mittels sql adapter in eine mariadb), bräuchte ich eine sortiermöglichkeit nach entfernung. 
hintergrund: ich hab eine ts ums eck und eine dazu gehörige tankkarte. somit sind die anderen ts nur für die preisentwicklung interessant, aber nicht fürs tanken selbst. 

danke

**Comment by HGlab01** [comment]
Hallo!
Die API unterstützt keine andere Sortierung. Der Adapter ist sehr generisch gebaut. Er nimmt einfach was er bekommt und erstellt damit States.
Du könntest aber die IDs durch iterieren und wenn die ID zu deiner Wunschtankstelle passt diesen Wert wegspeichern.
Ich fürchte aus Adaptersicht kann ich da nicht viel tun.

**Comment by HGlab01** [comment]
Hallo, würde es helfen wenn der Tree nach ID der Tankstelle geschehen würde?
Das könntet du ausprobieren durch Installation von
HGlab01/ioBroker.fuelpricemonitor#caa0ded7555fa2d3f6e2d299527c6df728934fec
über die "Katze"

**Comment by fwolf22** [comment]
Hallo,

ja danke, die Version mit den Tankstellen-ID's ist super. Es hat nur etwas länger gedauert, bis die Preise eingelesen hat, deswegen erst jetzt meine Antwort!

**Comment by HGlab01** [comment]
Hallo! Dann baue ich in den nächsten Tagen mal die Option ein, dass man oder ohne IDs die Preise bekommt.

**Comment by HGlab01** [comment]
Hallo, eine Version mit der Option ist vergfügbar. Test welcome!
Testbar durch Installation von
HGlab01/ioBroker.fuelpricemonitor#4faea5c6eeb28a49be33676a207b997b35db4ed0

![image](https://user-images.githubusercontent.com/54232526/114868778-94450900-9df6-11eb-9bbc-f64d75cc877f.png)

**Comment by HGlab01** [comment]
Feature available in v0.2.4
https://github.com/HGlab01/ioBroker.fuelpricemonitor/releases/tag/v0.2.4

**Comment by HGlab01** [comment]
Feature available in v0.2.4
https://github.com/HGlab01/ioBroker.fuelpricemonitor/releases/tag/v0.2.4
