### ISSUE TITLE
Latitude or longitude not set in main configuration

### ISSUE THREAD

**Issue by chrineuh** [HGlab01/ioBroker.fuelpricemonitor#66]
![grafik](https://user-images.githubusercontent.com/60777681/112716703-48cec780-8ee8-11eb-9547-fb6efffef332.png)

![grafik](https://user-images.githubusercontent.com/60777681/112716706-4b312180-8ee8-11eb-8612-5771c7a970ee.png)

Es Kommt immer der Fehler. 
benötige Weiz Austria bzw Graz Austria 

![grafik](https://user-images.githubusercontent.com/60777681/112716725-67cd5980-8ee8-11eb-8e2f-f0048f41ac51.png)

Habe die coordinaten von da.

**Comment by HGlab01** [comment]
Ebenso Hallo!
Du hast in der Haupt-Konfiguration keine Koordinaten eingetragen (nicht in der Adapter Konfiguration)
2 Möglichkeiten:
1. Keine der drei checkboxen aktivieren, dann wird für dein Home kein Treibstoff berechnet
2. Ganz oben auf das Schraubschlüssel Symbol klicken und dort die Koordinaten für deine iobroker Installation eintragen. Dann ist der Fehler weg und die Preise für zu Hause können ermittelt werden

**Comment by chrineuh** [comment]
Tanks
