### ISSUE TITLE
Info in Log: Method "deleteDevice" is deprecated and will be removed in js-controller 7, use "delObject" instead

### ISSUE THREAD

**Issue by latzi0710** [HGlab01/ioBroker.fuelpricemonitor#692]
**Describe the bug**  
Everytime adapter is started, the message `Method "deleteDevice" is deprecated and will be removed in js-controller 7, use "delObject" instead` is mentioned in the log

**To Reproduce**  
1. stop adapter
2. start adapter
3. take a look in the log after a while

**Versions:**  
 - Adapter version: 0.4.0
 - Admin version: 7.0.11
 - JS-Controller version: 6.0.6
 - Node version: 20.15.0
 - Operating system: debian bookworm

**Comment by HGlab01** [comment]
Thanks for raising the issue.
Will check/fix in the next days

**Comment by HGlab01** [comment]
fixed!
Can be tested in 0.4.1-alpha.0
Feedback welcome!

Easiest way to install in console with command
`iob upgrade iobroker.fuelpricemonitor@0.4.1-alpha.0`

**Comment by HGlab01** [comment]
will be closed with final version
