### ISSUE TITLE
Geoposition closest petrol station

### ISSUE THREAD

**Issue by Cyberraph** [HGlab01/ioBroker.fuelpricemonitor#731]
Hello all, 
Hello HGlab01,

I am not sure, 
if I am doing something wrong 
or something is wrong in the creation of datapoints for the closest petrol station.

For example I set the following Geopositions, which I got from https://www.gps-coordinates.net/.

Gaspoltshofen-Benzin
Gaspoltshofen-Diesel
48.134976346709536
13.728116446595454
=> this should be "Aspöck - Freie Tankstelle"

Ampflwang-Benzin
Ampflwang-Diesel
48.08074897870017
13.563780273867803
=> this should be "avanti - Ampflwang Siedlung 170"

Frankenburg-Benzin
Frankenburg-Diesel
48.06979710140276
13.492110726209582
=> this should be "AVIA Xpress (Automaten-Tankstelle)"

Zipf-Benzin
Zipf-Diesel
48.025970359863884
13.510162524555032
=> this should be "Lagerhaus Zipf"

But in the objects it creates mostly always the station "AVIA Xpress" as the first station, 
which is the nearest to my living place (geo position from iobroker settings).

The problem is that I dont get the price, because the stations I want are
mostly on the 5th place or higher, so there won´t be created a price datapoint.
It is just created a price datapoint object for the first five or also called 0,1,2,3,4 datapoints.

Can you help me with this issue?

Many thanks in advance for any respons.

Greetings Cyberraph (iobroker-newbie) :-)

PS:
As I see the prices for fuelpricemonitor are from e-control.
I have a ÖAMTC App, where prices are also displayed.
These prices also come from e-control.
In this App I saw that sometimes prices disappear.
So I guess also in io-broker there will be sometimes a price and sometimes no price displayed,
when io-brokes updates the datapoints and e-contro
l does´nt offer prices at this particular day-time / update-time.

Pictures from my io-broker fuelpricemonitor

![Additional Locations](https://github.com/user-attachments/assets/4074dafe-7752-4ff5-a869-29f53d51e8fc)

![Datapoints - HOME](https://github.com/user-attachments/assets/5ac216f7-b5fd-4974-9874-4450d1350414)

![Datapoints - AMPFLWANG](https://github.com/user-attachments/assets/1c027aab-6df7-453b-a05c-028ffcf49092)

![Datapoints - FRANKENBURG](https://github.com/user-attachments/assets/c3412de1-0a53-4a47-a6db-873c7a3e2b67)

![Datapoints - GASPOLTSHOFEN](https://github.com/user-attachments/assets/2d30e078-da57-4308-8300-afdd83e118dc)

![Datapoints - ZIPF](https://github.com/user-attachments/assets/a31dc784-b069-4f5c-bf8c-126bccb7bc5c)

![Example - Geoposition AMPFLWANG - avanti](https://github.com/user-attachments/assets/88f5dc96-38c9-42b5-b24e-e19f68c2365a)

**Comment by HGlab01** [comment]
Hi!
I guess it is, because there are always 5 others cheaper than the one you would like to know within the closest 10 stations?
You can use
https://www.spritpreisrechner.at/#/fossil
to understand better the result and maybe with this you can optimize the coordinates

For Gaspoltshofen it's obvious that "Aspöck - Freie Tankstelle" is not cheap enough within the closest 10 stations
![image](https://github.com/user-attachments/assets/1a134bbd-a147-4daf-8ba7-e975a17e03d8)

**Comment by Cyberraph** [comment]
Hello HGlab01,

oh, I am so sorry.

I thought it creates datapoints for the closest stations according their position next to the set geoposition.
And not the next 5 which have the cheapest prices.

That was not clear enough for me as I read the descriptions.

And in the adapter settings -> additional settings -> "Show cheapest staions over all locations"
just creates additional datapoints to compare the set geo-points within their cheapest stations themselfs.

![Additional settings](https://github.com/user-attachments/assets/c7f68408-f56b-467d-9e81-9321be336077)


Now I understand it.
Therefore the issue was sitting in front of the PC in this case.

And I have to search for another solution to get just my wanted stations.
No matter, if they are the cheapest or not.
I just want to compare the mentioned stations.
But I dont see to get it with this adapter, as the stations I want will sometimes fall out of the 5 cheapest.
Or I can make it happen to set a geo position to get what I want.

Thank you.
You have helped me enough.
